services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - PORT=3000
      # Configuración PostgreSQL (Easypanel) - hostname corregido basado en logs
      - DB_TYPE=postgres
      - DB_HOST=telehost_chatwaba
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=9ad22d8eb9a3fd48f227
      - DB_DATABASE=telehost
      - DB_SSL_MODE=disable
      - POSTGRES_PASSWORD=9ad22d8eb9a3fd48f227
      - DATABASE_URL=postgresql://postgres:9ad22d8eb9a3fd48f227@telehost_chatwaba:5432/telehost
      # TypeORM Configuration
      - TYPEORM_CONNECTION=postgres
      - TYPEORM_HOST=telehost_chatwaba
      - TYPEORM_PORT=5432
      - TYPEORM_USERNAME=postgres
      - TYPEORM_PASSWORD=9ad22d8eb9a3fd48f227
      - TYPEORM_DATABASE=telehost
      - TYPEORM_SYNCHRONIZE=true
      - TYPEORM_LOGGING=true
      - TYPEORM_ENTITIES=dist/**/*.entity.js
      - TYPEORM_MIGRATIONS=dist/database/migrations/*.js
      - TYPEORM_MIGRATIONS_RUN=true
      # Auth & Security
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret}
      - CORS_ORIGIN=${CORS_ORIGIN:-*}
      # AI Services (Optional)
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      # WhatsApp Integration (Optional)
      - EVOLUTION_API_URL=${EVOLUTION_API_URL:-}
      - EVOLUTION_API_KEY=${EVOLUTION_API_KEY:-}
      - WHATSAPP_INSTANCE=${WHATSAPP_INSTANCE:-}
      - WHATSAPP_API_URL=${WHATSAPP_API_URL:-}
      - WHATSAPP_DEFAULT_INSTANCE=${WHATSAPP_DEFAULT_INSTANCE:-}
    volumes:
      - uploads_data:/app/uploads
      - logs_data:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  uploads_data:
    driver: local
  logs_data:
    driver: local 